---
- name: Configure VyOS
  hosts: vyos-2
  gather_facts: false
  vars_files:
    - ./main_vars.yaml

  tasks:
  
    - name: Get Configuration
      import_role:
        name: common
      vars:
        resource: "{{ common.resource }}"
      when: get_config is defined
    
    - name: Bootstrap Router
      import_role:
        name: init
      when: bootstrap is defined

    - name: Configure Elastic IP
      import_role:
        name: elastic_ip
      when: elastic_ip is defined

    - name: Conifgure Port Forwarding
      import_role:
        name: port_forwarding
      when: port_forwarding is defined

    - name: Conifgure Ruleset
      import_role:
        name: firewall
      vars:
        name: "{{firewall_name}}"
        default_action: "{{firewall_default_action}}"
        rule_set_description: "{{firewall_rule_set_description}}"
        enable_default_log: "{{firewall_enable_default_log}}"
        interface: "{{ firewall_interface }}"
        direction: "{{ firewall_direction }}"
      when: firewalld is defined

    - name: Adding Firewall Role
      import_role:
        name: firewall
      vars:
        name: "{{firewall_name}}"
        rule_number: "{{firewall_rule_number}}"
        action: "{{firewall_action}}"
        rule_description: "{{firewall_rule_description}}"
        destination_address: "{{firewall_destination_address}}"
        destination_address_group: "{{firewall_destination_address_group}}"
        destination_network_group: "{{firewall_destination_network_group}}"
        destination_port_group: "{{firewall_destination_port_group}}"
        destination_port: "{{firewall_destination_port}}"
        source_address: "{{firewall_source_address}}"
        source_address_group: "{{firewall_source_address_group}}"
        source_network_group: "{{firewall_source_network_group}}"
        source_port_group: "{{firewall_source_port_group}}"
        source_port: "{{firewall_source_port}}"
        protocol: "{{firewall_protocol}}"
        disabled: "{{firewall_disabled}}"
        state: "{{firewall_state}}"
      when: firewalld is defined

    - name: Configure Subnet
      import_role:
        name: interfaces
      when: configure_network is defined

    - name: Configure DHCP
      import_role:
        name: services
      vars:
        action: "{{ dhcp_action }}"
        enabled: "{{ dhcp_enabled }}"
        network_name: "{{ dhcp_network_name }}"
        subnet: "{{ dhcp_subnet }}"
        lease: "{{ dhcp_lease }}"
        range: "{{ dhcp_range }}"
        start: "{{ dhcp_start }}"
        end: "{{ dhcp_end }}"
        default_router: "{{ dhcp_default_router }}"
        dns_server: "{{ dhcp_dns_server }}"
        old_subnet: "{{ dhcp_old_subnet }}"
    #   when: configure_dhcp is defined