---
- name: Configure VyOS
  hosts: all
  gather_facts: false
  vars_files:
    - ./main_vars.yaml

  tasks:
  
    - name: Get Configuration
      import_role:
        name: common
      vars:
        resource: "{{ common.resource }}"
      when: get_config is defined
    
    - name: Bootstrap Router
      import_role:
        name: init
      when: bootstrap is defined

    - name: Configure Elastic IP
      import_role:
        name: elastic_ip
      when: elastic_ip is defined

    - name: Conifgure Port Forwarding
      import_role:
        name: port_forwarding
      when: port_forwarding is defined

    - name: Conifgure Ruleset
      import_role:
        name: firewall
      vars:
        name: "{{firewall.name}}"
        default_action: "{{firewall.default_action}}"
        rule_set_description: "{{firewall.rule_set_description}}"
        enable_default_log: "{{firewall.enable_default_log}}"
        interface: "{{ firewall.interface }}"
        direction: "{{ firewall.direction }}"
      when: firewalld is defined

    - name: Adding Firewall Role
      import_role:
        name: firewall
      vars:
        name: "{{firewall.name}}"
        rule_number: "{{firewall.rule_number}}"
        action: "{{firewall.action}}"
        rule_description: "{{firewall.rule_description}}"
        destination_address: "{{firewall.destination_address}}"
        destination_address_group: "{{firewall.destination_address_group}}"
        destination_network_group: "{{firewall.destination_network_group}}"
        destination_port_group: "{{firewall.destination_port_group}}"
        destination_port: "{{firewall.destination_port}}"
        source_address: "{{firewall.source_address}}"
        source_address_group: "{{firewall.source_address_group}}"
        source_network_group: "{{firewall.source_network_group}}"
        source_port_group: "{{firewall.source_port_group}}"
        source_port: "{{firewall.source_port}}"
        protocol: "{{firewall.protocol}}"
        disabled: "{{firewall.disabled}}"
        state: "{{firewall.state}}"
      when: firewalld is defined

    - name: Configure Subnet
      import_role:
        name: interfaces
      when: configure_network is defined

    - name: Configure DHCP
      import_role:
        name: services
      vars:
        action: "{{ service.dhcp.action }}"
        enabled: "{{ service.dhcp.enabled }}"
        network_name: "{{ service.dhcp.network_name }}"
        subnet: "{{ service.dhcp.subnet }}"
        lease: "{{ service.dhcp.lease }}"
        range: "{{ service.dhcp.range }}"
        start: "{{ service.dhcp.start }}"
        end: "{{ service.dhcp.end }}"
        default_router: "{{ service.dhcp.default_router }}"
        dns_server: "{{ service.dhcp.dns_server }}"
        old_subnet: "{{ service.dhcp.old_subnet }}"
      when: configure_dhcp is defined