---
- name: Configure VyOS
  hosts: all
  gather_facts: false
  vars_files:
    - ./main_vars.yaml

  tasks:
    - name: Adding Bootstrap Role
      include_role:
        name: bootstrap
      when: default.bootstrap == "true"
    
    - name: Adding EIP Role
      include_role:
        name: elastic_ip
      when: eip.elastic_ip == "true"

    - name: Adding Port Forward Role
      include_role:
        name: interfaces
      # when: port_fwd.elastic_ip == "false"