- name: Add IPV4 Address
  vyos.vyos.vyos_config:
    lines:
    - set interfaces ethernet {{ interface }} address {{ address }}
  when: action == "add"

- name: Add IPV4 Address
  vyos.vyos.vyos_config:
    lines:
    - delete interfaces ethernet {{ interface }} address {{ address }}
  when: action == "remove"