---
- name: Configure Gateway
  vyos.vyos.vyos_config:
    lines:
    - set interfaces ethernet {{ network.interface }} address {{ network.ip_address }}
    - delete interfaces ethernet {{ network.interface }} address {{ network.old_ip_address }}
  when: service.dhcp.enabled == "false"

- name: Configure Gateway
  vyos.vyos.vyos_config:
    lines:
    - set interfaces ethernet {{ network.interface }} address {{ network.ip_address }}
    - set service dhcp-server shared-network-name {{ network.interface_description }} subnet {{ network.subnet }} default-router {{ network.default_router }}
    - delete interfaces ethernet {{ network.interface }} address {{ network.old_ip_address }}
  when: service.dhcp.enabled == "true"