- name: Add EIP on WAN Interface
  include_role:
    name: interfaces
    tasks_from: configure_ipv4
  vars:
    action: "add"
    interface: "{{ default.wan_interface }}"
    address: "{{ eip.address }}/32"

- name: CONFIGURE DNAT
  include_role:
    name: nat
    tasks_from: configure_dnat
  vars:
    action: "add"
    rule_number: "{{ dnat.rule_number }}"
    interface: "{{ default.wan_interface }}"
    protocol: "all"
    destination_address: "{{ eip.address }}"
    translation_address: "{{ dnat.translation_address }}"

- name: CONFIGURE SNAT
  include_role:
    name: nat
    tasks_from: configure_snat
  vars:
    action: "add"
    rule_number: "{{ snat.rule_number }}"
    interface: "{{ default.wan_interface }}"
    protocol: "all"
    source_address: "{{ snat.source_address }}"
    translation_address: "{{ eip.address }}"