---
- name: Remove EIP on WAN Interface
  import_role:
    role: interfaces
  vars:
    function: "configure_ipv4"
    action: "remove"
    interface: "{{ default.wan_interface }}"
    address: "{{ eip.address }}/32"

- name: CONFIGURE DNAT
  import_role:
    role: nat
  vars:
    function: "configure_dnat"
    action: "remove"
    rule_number: "{{ dnat.rule_number }}"
    interface: "{{ dnat.interface }}"
    protcol: "{{ dnat.protocol }}"
    destination_address: "{{ eip.address }}"
    translation_address: "{{ dnat.translation_address }}"

- name: CONFIGURE SNAT
  import_role:
    role: nat
  vars:
    function: "configure_snat"
    action: "remove"
    rule_number: "{{ snat.rule_number }}"
    interface: "{{ snat.interface }}"
    protcol: "{{ snat.protocol }}"
    source_address: "{{ snat.source_address }}"
    translation_address: "{{ eip.address }}"