- name: Unapply Ruleset
  vyos.vyos.vyos_firewall_interfaces:
    config:
    - access_rules:
      - afi: ipv4
        rules:
        - name: "{{ name }}"
          direction: "{{ direction }}"
      name: "{{ interface }}"
    state: deleted

- name: Remove Ruleset
  vyos.vyos.vyos_firewall_rules:
    config:
    - afi: ipv4
      rule_sets:
      - name: "{{ name }}"
    state: deleted