- name: Add Port Forwading Rule
  include_role:
    name: nat
    tasks_from: configure_dnat
  vars:
    action: "add"
    rule_number: "{{ dnat.rule_number }}"
    interface: "{{ default.wan_interface }}"
    protocol: "{{ port_fwd.protocol }}"
    destination_address: "{{ port_fwd.destination_address }}"
    translation_address: "{{ port_fwd.translation_address }}"

- name: Configure Ports
  vyos.vyos.vyos_config:
    lines:
    - set nat destination rule {{ dnat.rule_number }} destination port {{ port_fwd.destination_port }}
    - set nat destination rule {{ dnat.rule_number }} translation port {{ port_fwd.translation_port }}