---
- name: Add Port Forwading Rule
  import_role:
    role: nat
  vars:
    function: "configure_dnat"
    action: "add"
    rule_number: "{{ port_fwd.rule_number }}"
    interface: "{{ port_fwd.interface }}"
    protocol: "{{ port_fwd.protocol }}"
    destination_address: "{{ port_fwd.destination_address }}"
    translation_address: "{{ port_fwd.translation_address }}"

- name: Configure Ports
  vyos.vyos.vyos_config:
    lines:
    - set nat destination rule {{ port_fwd.rule_number }} destination port {{ port_fwd.destination_port }}
    - set nat destination rule {{ port_fwd.rule_number }} translation port {{ port_fwd.translation_port }}